---
# TODO: CIS benchmark fixing once it's released for 24.04

# TODO: add NTP server

- name: Set timezone
  community.general.timezone:
    name: America/Chicago

- name: Install unattended-upgrades
  ansible.builtin.package:
    name:
      - unattended-upgrades
    state: present

- name: Configure Auto Upgrades
  ansible.builtin.template:
    src: etc/apt/apt.conf.d/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"
  register: unattended_upgrades_50

- name: Restart unattended-upgrades # noqa: no-handler
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: restarted
    enabled: true
  when: unattended_upgrades_50.changed

- name: Install tools
  ansible.builtin.package:
    name:
      - net-tools
      - htop
      - unzip
      - gnupg2
      - vim
    state: present

- name: Install Step CLI
  # TODO: smallstep doesn't have a apt repo, so we need a way to keep this updated
  ansible.builtin.apt:
    deb: https://dl.smallstep.com/cli/docs-cli-install/latest/step-cli_amd64.deb

- name: Configure Step CLI
  ansible.builtin.shell: "step ca bootstrap --ca-url https://cuboid-topi.rmb1993-gmail-com.ca.smallstep.com --fingerprint eb136a5118931a2306964469705323521dda8c43d26ec67e1c5508eb123f9c70"
  args:
    creates: /etc/step/config/defaults.json
  environment:
    STEPPATH: "/etc/step"

- name: Copy SmallStep CA to System Store
  ansible.builtin.copy:
    remote_src: true
    src: /etc/step/certs/root_ca.crt
    dest: /usr/local/share/ca-certificates/smallstep.crt
    mode: "0644"
  register: smallstep_ca_copy

- name: Update CA Trust
  ansible.builtin.command: update-ca-certificates
  when: smallstep_ca_copy is changed

- name: Place SmallStep SystemD Renewal Service
  ansible.builtin.template:
    src: etc/systemd/system/cert-renewer@.service
    dest: /etc/systemd/system/cert-renewer@.service
    mode: "0644"
  register: smallstep_ca_systemd_renewal_service_template

- name: Place SmallStep SystemD Renewal Timer
  ansible.builtin.template:
    src: etc/systemd/system/cert-renewer@.timer
    dest: /etc/systemd/system/cert-renewer@.timer
    mode: "0644"
  register: smallstep_ca_systemd_renewal_timer_template

- name: Reload SystemD # noqa: no-handler
  ansible.builtin.systemd:
    daemon_reload: true
  when: smallstep_ca_systemd_renewal_service_template.changed or smallstep_ca_systemd_renewal_timer_template.changed

- name: Create default certificate key
  community.crypto.openssl_privatekey:
    path: /etc/ssl/private/default.pem.key
    curve: secp384r1
    type: ECC

- name: Create default CSR
  community.crypto.openssl_csr_pipe:
    privatekey_path: /etc/ssl/private/default.pem.key
    common_name: "{{ ansible_hostname }}"
    country_name: "US"
    extended_key_usage:
      - serverAuth
      - clientAuth
    organization_name: "Home Lab"
    organizational_unit_name: "Host Provisioning Self-Signed"
    state_or_province_name: "Minnesota"
    key_usage:
      - digitalSignature
    key_usage_critical: true
    use_common_name_for_san: true
  register: csr

- name: Create default certificate pem
  community.crypto.x509_certificate:
    path: /etc/ssl/private/default.pem
    csr_content: "{{ csr.csr }}"
    privatekey_path: /etc/ssl/private/default.pem.key
    provider: selfsigned

- name: Install Prometheus Node Exporter
  ansible.builtin.package:
    name:
      - prometheus-node-exporter
    state: present

- name: Start and Enable Prometheus Node Exporter
  ansible.builtin.systemd:
    service: prometheus-node-exporter
    state: started
    enabled: true

- name: Install Fluentbit keyring
  ansible.builtin.get_url:
    url: https://packages.fluentbit.io/fluentbit.key
    dest: /usr/share/keyrings/fluentbit-keyring.asc
    checksum: sha256:df248e2d7103ca62cb683c20a077198d0fb0a7f79dbf53a604af0317de3b4711
    mode: "0644"

- name: Add Fluentbit repo
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by=/usr/share/keyrings/fluentbit-keyring.asc]
      https://packages.fluentbit.io/ubuntu/noble noble main
    state: present

- name: Install fluentbit
  ansible.builtin.package:
    name: fluent-bit
    state: present

- name: Configure fluentbit
  ansible.builtin.template:
    src: etc/fluent-bit/fluent-bit.conf
    dest: /etc/fluent-bit/fluent-bit.conf
    mode: "0660"
    owner: root
    group: root
  register: fluentbit_config

- name: Configure fluentbit Parsers
  ansible.builtin.template:
    src: etc/fluent-bit/parsers.conf
    dest: /etc/fluent-bit/parsers.conf
    mode: "0666"
    owner: root
    group: root
  register: fluentbit_parsers

- name: Create fluentbit state directory
  ansible.builtin.file:
    path: /var/lib/fluent-bit
    mode: "0755"
    owner: root
    group: root
    state: directory

- name: Start fluentbit
  ansible.builtin.systemd:
    service: fluent-bit
    state: started
    enabled: true

- name: Restart fluentbit if config changed # noqa: no-handler
  ansible.builtin.systemd:
    name: fluent-bit
    state: restarted
  when: fluentbit_config.changed or fluentbit_parsers.changed
